################################################################################
# _config_qa.yml                                                            #
#                                                                              #
# This config file will be used when building the site for deployment to the   #
# quality assurance (QA) tier.                                                 #
################################################################################

tier: qa
url: https://qa.bengodfrey.net

# Use reCAPTCHA testing key for local development. See also:
# https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
recaptcha_site_id: 6LekpXceAAAAAG1Obo3qshDu7i4a7Tz7gKYElbMh
