################################################################################
# _config_build.yml                                                            #
#                                                                              #
# This config file will be used when building the site for CI builds on the    #
# GitHub actions platform or builds that will be deployed to the QA tier.      #
#                                                                              #
# See also: .github/workflows/ci.yml                                           #
################################################################################

tier: ci

# Cause the build to fail if there is a YAML syntax error in page front matter.
strict_front_matter: true

# Cause the build to fail when liquid has problems.
liquid:
  error_mode: strict
  # strict_variables: true # seems not to work with project var usage in layouts
  strict_filters: true

# Mirror GitHub pages produciton configuration.
# See also: https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll
lsi: false
# safe: true # FIXME see ticket #65 for details.
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
