
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ben's Code Projects
email: BenJetson@users.noreply.github.com
description: >- 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bengodfrey.net" #interwebz
twitter_username: BenJetson
github_username:  BenJetson
profileIMG: https://avatars1.githubusercontent.com/u/10427974?s=460&v=4

# Build settings
remoteURL: "https://www.bengodfrey.net"
localURL: "http://localhost:4000"
underConstruction: false
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-octicons
  - rouge
  - github-pages
sass:
  style: compressed
permalink: /blog/:year/:month/:day-:title

# Collection Settings
# See also: https://jekyllrb.com/docs/collections/
collections:
  projects:
    featured: false
    layout: project
    output: true

# Page defaults
defaults:
  -
    scope:
      path: ""
    values: 
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
      image: "site.url/img/felipe-santana-309268.jpg"
      image-credit: Felipe Santana on Unsplash
  -
    scope:
      path: "_projects"
    values:
      layout: "project"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
