################################################################################
# _config_dev.yml                                                              #
#                                                                              #
# This config file will be used by the Makefile when hosting any instances of  #
# the Jekyll server on local development machines.                             #
################################################################################

# Reload the page automatically in the browser when its content is edited.
livereload: true

# Process and render draft posts.
show_drafts: true

# Cause the build to fail if there is a YAML syntax error in page front matter.
strict_front_matter: true

# Plugins used for the development server.
# WARNING: any plugins enabled in _config.yml should also appear here!
plugins:
  # GitHub Pages mandatory plugins
  # See also: https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

  # Site plugins
  - jekyll-feed
  - jekyll-octicons
  - rouge

  # Development-only plugins.
  - jekyll-admin
