################################################################################
# _config.yml                                                                  #
#                                                                              #
# This config file is the global configuration file, which will be applied in  #
# all production and development builds.                                       #
################################################################################

# Site settings
title: Ben's Code Projects
email: BenJetson@users.noreply.github.com
description: >-
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bengodfrey.net" #interwebz
twitter_username: BenJetson
github_username: BenJetson
profileIMG: https://avatars1.githubusercontent.com/u/10427974?s=460&v=4

# Build settings
remoteURL: "https://www.bengodfrey.net"
localURL: "http://localhost:4000"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-octicons
  - rouge
  - github-pages
sass:
  style: compressed
permalink: /blog/:year/:month/:day-:title

# Collection Settings
# See also: https://jekyllrb.com/docs/collections/
collections:
  projects:
    output: true
    sort_by: rank # Not supported in Jekyll 3.8.5 -- requires at least 3.8.6?

# Page defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
      image: "site.url/img/felipe-santana-309268.jpg"
      image-credit: Felipe Santana on Unsplash
      comments: true
  - scope:
      path: "_projects"
    values:
      layout: "project"
      username: ""
      repo: ""
      issues: false
      wiki: false
      featured: false
      photo: https://dummyimage.com/400x400/ff0000/ffffff&text=MISSING
      comments: true

# Exclude from processing.
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
