################################################################################
# _config.yml                                                                  #
#                                                                              #
# This config file is the global configuration file, which will be applied in  #
# all production and development builds.                                       #
################################################################################

# Site settings
title: Ben's Code Projects
email: BenJetson@users.noreply.github.com
description: >-
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bengodfrey.net" #interwebz
twitter_username: BenJetson
github_username: BenJetson
repository: BenJetson/benjetson.github.io
profileIMG: https://avatars1.githubusercontent.com/u/10427974?s=460&v=4

# Build settings
tier: prod
remoteURL: "https://www.bengodfrey.net"
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
sass:
  style: compressed
permalink: /blog/:year/:month/:day-:title

# Plugins used for production.
# WARNING: any changes to plugins should be made to _config_dev.yml also!
plugins:
  # GitHub Pages mandatory plugins
  # See also: https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

  # Site plugins
  - jekyll-feed
  - jekyll-octicons
  - rouge

# Collection Settings
# See also: https://jekyllrb.com/docs/collections/
collections:
  projects:
    output: true
    sort_by: rank # Not supported in Jekyll 3.8.5 -- requires at least 3.8.6?

# Page defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
      comments: true
  - scope:
      path: "_projects"
    values:
      layout: "project"
      username: ""
      repo: ""
      issues: false
      wiki: false
      featured: false
      photo: https://dummyimage.com/400x400/ff0000/ffffff&text=MISSING
      comments: true

# Exclude from processing.
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
