################################################################################
# _config_build.yml                                                            #
#                                                                              #
# This config file will be used when building the site for CI builds on the    #
# GitHub actions platform.                                                     #
#                                                                              #
# See also: .github/workflows/ci.yml                                           #
################################################################################

# Cause the build to fail if there is a YAML syntax error in page front matter.
strict_front_matter: true

# Cause the build to fail when liquid has problems.
liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

# Mirror GitHub pages produciton configuration.
# See also: https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
