title: Ben's Code Projects
description: >
  Homepage to showcase all of my various
  code projects.

url: "http://www.bgcode.net"
        # URL for web hosting
#url: "http://localhost:4000"
        # URL for local server

closed: true
    # Removes all content and displays
    #   maintenance warning modal.

# Build Configuration
markdown: kramdown
safe: true
gems:
  - jekyll-mentions
  - gemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - vendor/*
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"