################################################################################
# _config_qa.yml                                                            #
#                                                                              #
# This config file will be used when building the site for deployment to the   #
# quality assurance (QA) tier.                                                 #
################################################################################

tier: qa
url: https://qa.bengodfrey.net

# Development contact form.
contact_form_id: WzEwOSwxMjEsMTIxLDExMSwxMTksMTIyLDEwNiwxMTJd

# Use reCAPTCHA testing key for local development. See also:
# https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
recaptcha_site_id: 6Leg5fwhAAAAAEt01he0_xfyIF59TeK3NYR5PrCA
