---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: next/projects
  label: Project Pages
  create: documents
  match: "**/*"
  templates:
  - project-page
- type: directory
  path: next/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: next/public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:-:month:-:day:-:filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv/next"
  instant_preview_command: yarn dev
