# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SHCK_VERSION: "v0.7.1"
      ECLINT_VERSION: "0.3.2"
      ECLINT_GITLAB_UPLOAD_TAG: "38b6bd1c60e02d07b9c8b83ab115ce52"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python Dependency Cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python/3.8.3/x64
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements.txt') }}
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r scripts/requirements.txt

      - name: Install ShellCheck
        run: |
          set -e;
          mkdir -p /tmp/shck_install
          cd /tmp/shck_install
          wget "https://github.com/koalaman/shellcheck/releases/download/${SHCK_VERSION}/shellcheck-${SHCK_VERSION}.linux.x86_64.tar.xz"
          tar --xz -xvf shellcheck-"${SHCK_VERSION}".linux.x86_64.tar.xz
          sudo cp shellcheck-"${SHCK_VERSION}"/shellcheck /usr/bin/
          shellcheck --version
          rm -rf /tmp/shck_install

      - name: Install ECLint
        run: |
          set -e
          mkdir -p /tmp/eclint_install
          cd /tmp/eclint_install
          wget "https://gitlab.com/greut/eclint/uploads/${ECLINT_GITLAB_UPLOAD_TAG}/eclint_${ECLINT_VERSION}_linux_x86_64.tar.gz"
          tar -xzvf eclint_"${ECLINT_VERSION}"_linux_x86_64.tar.gz
          sudo cp eclint /usr/bin
          eclint --version
          rm -rf /tmp/eclint_install

      - name: Run Linters
        run: ./scripts/lint.sh
